name: MagicMoment
description: "mobile application for editing images and creating collages"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.273
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path: ^1.8.3
  http: ^1.3.0
  device_info_plus: ^10.1.2
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  image: ^4.5.4
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_colorpicker: ^1.0.3
  flutter_cache_manager: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_image_compress: ^2.0.4
  throttling: ^2.0.1
  flutter_dotenv: ^5.2.1
  universal_html: ^2.2.4
  share_plus: ^11.0.0
  permission_handler: ^11.3.1
  gallery_saver_plus: ^3.2.4

dev_dependencies:
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.14.0
  build_runner: ^2.4.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconMM.webp"

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/icons/iconMM.webp
    - lib/assets/placeholder.jpg
    - lib/assets/icons/photos.png
    - lib/assets/google_fonts/Oi-Regular.ttf
    - lib/assets/google_fonts/LilitaOne-Regular.ttf
    - lib/assets/google_fonts/PTSansNarrow-Regular.ttf
    - lib/assets/google_fonts/Comfortaa-VariableFont_wght.ttf
    - lib/assets/stickers/fun1.png
    - lib/assets/stickers/fun2.png
    - lib/assets/stickers/fun3.png
    - lib/assets/stickers/fun4.png
    - lib/assets/stickers/fun5.png
    - lib/assets/stickers/animals1.png
    - lib/assets/stickers/animals2.png
    - lib/assets/stickers/animals3.png
    - lib/assets/stickers/animals4.png
    - lib/assets/stickers/animals5.png
    - lib/assets/stickers/animals6.png
    - lib/assets/stickers/animals7.png
    - lib/assets/stickers/animals8.png
    - lib/assets/stickers/birthday1.png
    - lib/assets/stickers/birthday2.png
    - lib/assets/stickers/birthday3.png
    - lib/assets/stickers/birthday4.png
    - lib/assets/stickers/birthday5.png
    - lib/assets/stickers/birthday6.png
    - lib/assets/stickers/birthday7.png
    - lib/assets/stickers/nature1.png
    - lib/assets/stickers/nature2.png
    - lib/assets/stickers/nature3.png
    - lib/assets/stickers/nature4.png
    - lib/assets/stickers/nature5.png
    - lib/assets/stickers/nature6.png
    - lib/assets/stickers/nature7.png
    - lib/assets/stickers/ch1.png
    - lib/assets/stickers/ch2.png
    - lib/assets/stickers/ch3.png
    - lib/assets/stickers/ch4.png
    - lib/assets/stickers/ch5.png
    - lib/assets/stickers/ch6.png
    - lib/assets/stickers/ch7.png
    - lib/assets/stickers/ch8.png
    - lib/assets/stickers/ch9.png
    - lib/assets/stickers/ch10.png
    - lib/assets/stickers/ch11.png

  fonts:
    - family: Oi-Regular
      fonts:
        - asset: lib/assets/google_fonts/Oi-Regular.ttf
    - family: LilitaOne-Regular
      fonts:
        - asset: lib/assets/google_fonts/LilitaOne-Regular.ttf
    - family: PTSansNarrow-Regular
      fonts:
        - asset: lib/assets/google_fonts/PTSansNarrow-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: lib/assets/google_fonts/Comfortaa-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/google_fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
    - family: Arial
      fonts:
        - asset: lib/assets/google_fonts/Arial.ttf
    - family: Courier
      fonts:
        - asset: lib/assets/google_fonts/CourierPrime-Regular.ttf
    - family: Times New Roman
      fonts:
        - asset: lib/assets/google_fonts/times.ttf
    - family: Impact
      fonts:
        - asset: lib/assets/google_fonts/impact.ttf
    - family: Comic Sans MS
      fonts:
        - asset: lib/assets/google_fonts/Comic Sans MS.ttf
    - family: Verdana
      fonts:
        - asset: lib/assets/google_fonts/VERDANAI.ttf