name: MagicMoment
description: "mobile application for editing images and creating collages"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.273
  battery_plus: ^5.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  provider: ^6.0.0
  permission_handler: ^11.4.0
  sqflite: ^2.2.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconMM.webp"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/iconMM.webp
    - lib/assets/icons/photos.png
    - lib/assets/google_fonts/Oi-Regular.ttf
    - lib/assets/google_fonts/LilitaOne-Regular.ttf
    - lib/assets/google_fonts/PTSansNarrow-Regular.ttf
    - lib/assets/google_fonts/Comfortaa-VariableFont_wght.ttf

  fonts:
    - family: Oi-Regular
      fonts:
        - asset: lib/assets/google_fonts/Oi-Regular.ttf
    - family: LilitaOne-Regular
      fonts:
        - asset: lib/assets/google_fonts/LilitaOne-Regular.ttf
    - family: PTSansNarrow-Regular
      fonts:
        - asset: lib/assets/google_fonts/PTSansNarrow-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: lib/assets/google_fonts/Comfortaa-VariableFont_wght.ttf