name: MagicMoment
description: "mobile application for editing images and creating collages"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.273
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.1
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  image_collage_widget: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  image_gallery_saver: ^2.0.3
  flutter_localizations:
    sdk: flutter
  image: ^4.5.4
  path_provider: ^2.0.11
  image_picker: ^1.1.2
  universal_html: ^2.2.4
  image_filter_pro: ^0.1.11
  image_cropper:  ^9.1.0
  pro_image_editor: ^6.2.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconMM.webp"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/iconMM.webp
    - lib/assets/icons/photos.png
    - lib/assets/google_fonts/Oi-Regular.ttf
    - lib/assets/google_fonts/LilitaOne-Regular.ttf
    - lib/assets/google_fonts/PTSansNarrow-Regular.ttf
    - lib/assets/google_fonts/Comfortaa-VariableFont_wght.ttf

  fonts:
    - family: Oi-Regular
      fonts:
        - asset: lib/assets/google_fonts/Oi-Regular.ttf
    - family: LilitaOne-Regular
      fonts:
        - asset: lib/assets/google_fonts/LilitaOne-Regular.ttf
    - family: PTSansNarrow-Regular
      fonts:
        - asset: lib/assets/google_fonts/PTSansNarrow-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: lib/assets/google_fonts/Comfortaa-VariableFont_wght.ttf